// server/models/Message.js
//
// WHY THIS TABLE EXISTS — the chat system between customer and artist:
//
// Every order has a conversation thread. Messages come from three sources:
//   'customer' — the customer typed a message (e.g. revision request details)
//   'admin'    — the artist typed a reply from the admin dashboard
//   'system'   — auto-generated by the server when something happens
//                (e.g. "Proof uploaded — please review", "Order shipped to [address]")
//
// The customer sees this thread on their order page.
// The admin/artist sees it in the order detail panel on the dashboard.

module.exports = (sequelize, DataTypes) => {
  const Message = sequelize.define('Message', {
    message_id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },

    // FK → Orders.order_id
    order_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: { model: 'Orders', key: 'order_id' },
    },

    // Who sent the message
    sender_type: {
      type: DataTypes.ENUM('customer', 'admin', 'system'),
      allowNull: false,
    },
    // The actual ID of the sender (null for system messages)
    // If sender_type = 'customer' → this is the customer_id (INTEGER)
    // If sender_type = 'admin'    → this is the admin id (UUID)
    // Stored as STRING to handle both INTEGER and UUID without conflict
    sender_id: {
      type: DataTypes.STRING,
      allowNull: true,
    },

    // The message content
    message_text: {
      type: DataTypes.TEXT,
      allowNull: false,
    },

    // Has the other party seen this message?
    is_read: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
    },
    read_at: {
      type: DataTypes.DATE,
      allowNull: true,
    },
  }, {
    tableName: 'Messages',
    timestamps: true,   // createdAt = when message was sent
  });

  // ── Associations ─────────────────────────────────────────────────────────────
  Message.associate = (models) => {
    Message.belongsTo(models.Order, {
      foreignKey: 'order_id',
      as: 'order',
    });
  };

  return Message;
};